sudo: required
services:
    - docker
before_install:
    - docker build -t react-docker-sg -f Dockerfile.dev .
script:
    - docker run -e CI=true react-docker-sg npm run test
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    name: 'react-docker-sg'
    env: 'React-docker-sg-env'
    bucket-name: 'elasticbeanstalk-us-east-1-097020882795'
    bucket-path: 'react-docker-sg'
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: '$AWS_SECRET_KEY'
    skip_cleanup: true
