sudo: required
services:
    - docker
before_install:
    - docker build -t pavitpim40/react-docker -f Dockerfile.dev .
script:
    - docker run -e CI=true pavitpim40/react-docker npm run test
deploy:
    provider: elasticbeanstalk
    region: 'us-east-1'
    name: 'docker-react'
    env: 'Docker-react-env'
    bucket-name: 'elasticbeanstalk-us-east-1-097020882795'
    bucket-path: 'docker-react'
    on:
        branch: main
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: '$AWS_SECRET_KEY'
